name: HealCMD
version: 1.0
api: 3.0.0
author:
  - NxtGamerHD
  - RageCraftPlugins
main: Heal\NxtGamerHD\main

commands:
  heal:
    description: "Heile dich!"
    permission: heal.use
    usage: "/heal"

permissions:
  heal.use:
    default: op
    description: "Erlaubt es dir /heal zu nutzen!"
